### ISSUE TITLE
Issue with Playback

### ISSUE THREAD

**Issue by aravindnc** [techiesneh/sneh-iptv-m3u#2]
@techiesneh 
I have been trying to play the m3u playlist files in VLC player. The problem is that the playback stops after 10seconds to 1 min.
In some playlists it keeps playing the next channel after every 5-10 seconds.

Tried with kodi also still the same, playback stops after x seconds on below playlist.
https://raw.githubusercontent.com/techiesneh/sneh-iptv-m3u/main/Indian%20Playlists/sneh-watchindia.m3u

Any advice?

**Comment by techiesneh** [comment]
use in mobile app tivimates it works

**Comment by aravindnc** [comment]
Sorry, I don't use mobile apps much, I'm looking for a web/windows alternative. 
Anyway thanks.

**Comment by aravindnc** [comment]
Update - Tivimate in windows is working fine with the playlist.
